import { z } from "zod";

const ReactionSchema = z.object({
  name: z.string(),
  users: z.array(z.string()),
  count: z.number(),
});

const EditedInfoSchema = z.object({
  user: z.string(),
  ts: z.string(),
});

const FileElementSchema = z.object({
  id: z.string().optional(),
  created: z.number().optional(),
  timestamp: z.number().optional(),
  name: z.string().optional(),
  title: z.string().optional(),
  mimetype: z.string().optional(),
  filetype: z.string().optional(),
  pretty_type: z.string().optional(),
  user: z.string().optional(),
  size: z.number().optional(),
  mode: z.string().optional(),
  is_external: z.boolean().optional(),
  external_type: z.string().optional(),
  is_public: z.boolean().optional(),
  public_url_shared: z.boolean().optional(),
  display_as_bot: z.boolean().optional(),
  username: z.string().optional(),
  url_private: z.string().optional(),
  url_private_download: z.string().optional(),
  thumb_64: z.string().optional(),
  thumb_80: z.string().optional(),
  thumb_360: z.string().optional(),
  thumb_360_w: z.number().optional(),
  thumb_360_h: z.number().optional(),
  thumb_480: z.string().optional(),
  thumb_480_w: z.number().optional(),
  thumb_480_h: z.number().optional(),
  thumb_160: z.string().optional(),
  thumb_360_gif: z.string().optional(),
  thumb_480_gif: z.string().optional(),
  thumb_720: z.string().optional(),
  thumb_720_w: z.number().optional(),
  thumb_720_h: z.number().optional(),
  thumb_800: z.string().optional(),
  thumb_800_w: z.number().optional(),
  thumb_800_h: z.number().optional(),
  thumb_960: z.string().optional(),
  thumb_960_w: z.number().optional(),
  thumb_960_h: z.number().optional(),
  thumb_1024: z.string().optional(),
  thumb_1024_w: z.number().optional(),
  thumb_1024_h: z.number().optional(),
  image_exif_rotation: z.number().optional(),
  original_w: z.number().optional(),
  original_h: z.number().optional(),
  permalink: z.string().optional(),
  permalink_public: z.string().optional(),
});

export const SlackMessageSchema = z.object({
  type: z.string().optional(),
  subtype: z.string().optional(),
  text: z.string().optional(),
  ts: z.string().optional(),
  user: z.string().optional(),
  team: z.string().optional(),
  blocks: z.array(z.unknown()).optional(),
  attachments: z.array(z.unknown()).optional(),
  files: z.array(FileElementSchema).optional(),
  reactions: z.array(ReactionSchema).optional(),
  reply_count: z.number().optional(),
  reply_users: z.array(z.string()).optional(),
  reply_users_count: z.number().optional(),
  latest_reply: z.string().optional(),
  edited: EditedInfoSchema.optional(),
  thread_ts: z.string().optional(),
  parent_user_id: z.string().optional(),
});
